// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QuanLyBanHangOnline.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122170259_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("quanlybanhangonline.Model.Cart", b =>
                {
                    b.Property<int>("IdCart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCart"), 1L, 1);

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdCart");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("QuanLyBanHangOnline.Models.Account", b =>
                {
                    b.Property<int>("IdAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccount"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAccount");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("quanlybanhangonline.Models.AccountOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("AccountOtps");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.CartDetail", b =>
                {
                    b.Property<int>("IdCartDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCartDetail"), 1L, 1);

                    b.Property<int>("IdCart")
                        .HasColumnType("int");

                    b.Property<int>("IdSP")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdCartDetail");

                    b.HasIndex("IdCart");

                    b.HasIndex("IdSP");

                    b.ToTable("CartDetail");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Import", b =>
                {
                    b.Property<int>("IdImport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImport"), 1L, 1);

                    b.Property<int>("IdAccount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdImport");

                    b.HasIndex("IdAccount");

                    b.ToTable("Import");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.ImportDetail", b =>
                {
                    b.Property<int>("IdImportDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImportDetail"), 1L, 1);

                    b.Property<int>("IdImport")
                        .HasColumnType("int");

                    b.Property<int>("IdSP")
                        .HasColumnType("int");

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdImportDetail");

                    b.HasIndex("IdImport");

                    b.HasIndex("IdSP");

                    b.ToTable("ImportDetail");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Order", b =>
                {
                    b.Property<int>("IdDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDH"), 1L, 1);

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDH");

                    b.HasIndex("IdUser");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.OrderDetail", b =>
                {
                    b.Property<int>("IdOrderDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrderDetail"), 1L, 1);

                    b.Property<int>("IdDH")
                        .HasColumnType("int");

                    b.Property<int>("IdSP")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdOrderDetail");

                    b.HasIndex("IdDH");

                    b.HasIndex("IdSP");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Product", b =>
                {
                    b.Property<int>("IdSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSP"), 1L, 1);

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("IdSP");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.ProductDetail", b =>
                {
                    b.Property<int>("IdSP")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSP");

                    b.ToTable("ProductDetail");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Review", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReview"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSP")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("IdReview");

                    b.HasIndex("IdSP");

                    b.HasIndex("IdUser");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Admin", b =>
                {
                    b.HasBaseType("QuanLyBanHangOnline.Models.Account");

                    b.ToTable("Admins", (string)null);

                    b.HasData(
                        new
                        {
                            IdAccount = 1,
                            Email = "admin@gmail.com",
                            Password = "$2a$11$BbiFgNGQCSSOxZH6x1m8uOm.TrKLWR8NAuGHH6JGBsUIQwwSO.gtK",
                            RoleType = "Admin"
                        });
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Staff", b =>
                {
                    b.HasBaseType("QuanLyBanHangOnline.Models.Account");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("RoleId");

                    b.ToTable("Staffs", (string)null);

                    b.HasData(
                        new
                        {
                            IdAccount = 2,
                            Email = "staff@gmail.com",
                            Password = "$2a$11$8HPqtd5cLUgcyBSXkDkL2OAyiy1nzpCyvY/Jd6M.L9FW4WOOp4Q5q",
                            RoleType = "Staff"
                        });
                });

            modelBuilder.Entity("quanlybanhangonline.Models.User", b =>
                {
                    b.HasBaseType("QuanLyBanHangOnline.Models.Account");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            IdAccount = 3,
                            Email = "user@gmail.com",
                            Password = "$2a$11$7OdFyxZMhViCzGGSRW3ob.l/QkS2rqtO5R6fEPmnDWJOGuxYjNYrC",
                            RoleType = "User"
                        },
                        new
                        {
                            IdAccount = 4,
                            Email = "nxtql99@gmail.com",
                            Password = "$2a$11$.kJyjusLlOVTnwgr/8tjMepHgAJzHAef2DviSM5dkf7Qli4J8evcu",
                            RoleType = "User"
                        },
                        new
                        {
                            IdAccount = 5,
                            Email = "ndt@gmail.com",
                            Password = "$2a$11$Oj93lz3afb4lApk4kZ66cuOD9caTy/.JQDMBQBQ76b1B04/OdBykO",
                            RoleType = "User"
                        });
                });

            modelBuilder.Entity("quanlybanhangonline.Model.Cart", b =>
                {
                    b.HasOne("quanlybanhangonline.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.AccountOtp", b =>
                {
                    b.HasOne("QuanLyBanHangOnline.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Email")
                        .HasPrincipalKey("Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.CartDetail", b =>
                {
                    b.HasOne("quanlybanhangonline.Model.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("IdCart")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlybanhangonline.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Import", b =>
                {
                    b.HasOne("QuanLyBanHangOnline.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.ImportDetail", b =>
                {
                    b.HasOne("quanlybanhangonline.Models.Import", "Import")
                        .WithMany("ImportDetails")
                        .HasForeignKey("IdImport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlybanhangonline.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Import");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Order", b =>
                {
                    b.HasOne("quanlybanhangonline.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.OrderDetail", b =>
                {
                    b.HasOne("quanlybanhangonline.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("IdDH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlybanhangonline.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.ProductDetail", b =>
                {
                    b.HasOne("quanlybanhangonline.Models.Product", "Product")
                        .WithOne("ProductDetail")
                        .HasForeignKey("quanlybanhangonline.Models.ProductDetail", "IdSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Review", b =>
                {
                    b.HasOne("quanlybanhangonline.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlybanhangonline.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Admin", b =>
                {
                    b.HasOne("QuanLyBanHangOnline.Models.Account", null)
                        .WithOne()
                        .HasForeignKey("quanlybanhangonline.Models.Admin", "IdAccount")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Staff", b =>
                {
                    b.HasOne("QuanLyBanHangOnline.Models.Account", null)
                        .WithOne()
                        .HasForeignKey("quanlybanhangonline.Models.Staff", "IdAccount")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("quanlybanhangonline.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.User", b =>
                {
                    b.HasOne("QuanLyBanHangOnline.Models.Account", null)
                        .WithOne()
                        .HasForeignKey("quanlybanhangonline.Models.User", "IdAccount")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("quanlybanhangonline.Model.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Import", b =>
                {
                    b.Navigation("ImportDetails");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("quanlybanhangonline.Models.Product", b =>
                {
                    b.Navigation("ProductDetail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
